language: csharp
solution: Dybdc.Data.Sql.Builder.sln
mono: none
dotnet: 2.0.2
install:
  - dotnet restore ./Dybdc.Data.Sql.Builder.sln
script:
  - dotnet build -c Release /p:TreatWarningsAsErrors=true Dybdc.Data.Sql.Builder.sln 
  - cd ./Dybdc.Data.Sql.Builder.Test.Unit
  - dotnet test